name: Test

on: [push]

jobs:
  test:
    # where it is going to run
    runs-on: ubuntu-latest
    # what we are going to do
    steps:
        # download repository
      - uses: actions/checkout@v3
        # set up java
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
        # set up selenoid
      - uses: Xotabu4/selenoid-github-action@v2
        # run tests
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
        # Report generation
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
          # Report publication
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history